export const SupportChat: { msg: string; from: 'support' | 'me' }[] = [
	{ msg: 'Hello man, I have issues with my funds.', from: 'me' },
	{ msg: 'Can you please explain further', from: 'support' },
	{ msg: 'I sent 5,000 naira.', from: 'me' },
	{ msg: "and I haven't received it", from: 'me' },
	{ msg: 'Okay. Can you send your transaction hash?', from: 'support' },
	{ msg: 'Sure', from: 'me' },
	{ msg: '0x20F50b8832f87104853df3FdDA47Dd464f885a49', from: 'me' },
	{ msg: 'Seen', from: 'support' },
	{ msg: 'I will work on it right away', from: 'support' },
	{ msg: 'Alright', from: 'me' },
	{ msg: 'Thanks', from: 'me' },
	{ msg: 'You are welcome', from: 'support' },
	{ msg: 'Hello man', from: 'me' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'me' },
	{ msg: 'The example below builds on the', from: 'support' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Connect Wallet guide and uses the', from: 'me' },
	{ msg: 'Hello man', from: 'support' },
	{
		msg: 'The following guide teaches you how to send transactions in Wagmi.',
		from: 'support'
	},
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'me' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'me' },
	{ msg: 'Hello man', from: 'support' },
	{ msg: 'Hello man', from: 'me' }
];
