
CREATE TABLE airtime (
  id   BIGSERIAL PRIMARY KEY,
  network TEXT      NOT NULL,
  country  TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
