services:
  postgres:
    image: postgres:15
    container_name: happy_container
    environment:
      POSTGRES_USER: happy_user
      POSTGRES_PASSWORD: happy_pass
      POSTGRES_DB: happy_db
    ports:
      - "5435:5432"
    volumes:
      - happy_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U happy_user -d happy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  happy_data:
